### PR TITLE
Link to a page that is more useful.

### PR DESCRIPTION
**Pull request by mcgitty**

### CODE REVIEW

**Review by alhambrav — CHANGES_REQUESTED** [review]
A reference to the file for debugging ssh issues would be better instead of including the file like so:

.. note::
      For more information on errors that a user may encounter when using ssh keys with Crafter CMS, see :ref:`debugging_ssh_issues`

**Comment by mcgitty** [comment]
Please correct the formatting as see fit.

**Review by alhambrav — APPROVED** [review]

**Comment by mcgitty** [comment]
@alhambrav The reference in the Note doesn't render right:

https://docs.craftercms.org/en/3.1/site-administrators/remote-repositories.html#add-a-repository

**Comment by alhambrav** [comment]
@mcgitty Note rendering is now fixed.  Thank you.

**Pull request merged**
