### PR TITLE
Add missing definition of 'entities' (in example)

### PR DESCRIPTION
**Pull request by mcgitty**

### CODE REVIEW

**Comment by sumerjabri** [comment]
@alhambrav you may check with @dejan-brkic to validate and add any other missing parameter definitions.

**Comment by mcgitty** [comment]
Please also check this API document, which seem under documented. The example shows more parameter than formally defined, such ask schedule, items, publishChannel, etc.

https://docs.craftercms.org/en/3.1/developers/projects/studio/api/workflow/go-live.html

It seems to be a duplicate API of "Publish Items" logically.

**Comment by mcgitty** [comment]
My PR was meant to add definition of 'entities', not to delete the definition of 'item'. Please double check.

**Comment by mcgitty** [comment]
Hi, please see comment:

https://github.com/craftercms/docs/pull/1247#issuecomment-843349092

Thanks

--Michael

From: Sumer Jabri ***@***.***>
Reply-To: craftercms/docs ***@***.***>
Date: Tuesday, May 18, 2021 at 9:05 AM
To: craftercms/docs ***@***.***>
Cc: Michael Chen ***@***.***>, Author ***@***.***>
Subject: Re: [craftercms/docs] Add missing definition of 'entities' (in example) (#1247)


Merged #1247<https://github.com/craftercms/docs/pull/1247> into 3.1.

**Comment by sumerjabri** [comment]
@mcgitty `item` is part of `entities`. @dejan-brkic can confirm.

**Pull request merged**
