### PR TITLE
Update examples for Studio site plugins #4627

### PR DESCRIPTION
**Pull request by alhambrav**
### Ticket reference or full description of what's in the PR
Update examples for Studio site plugins https://github.com/craftercms/craftercms/issues/4627

### CODE REVIEW

**Review by jdrossl — APPROVED** [review]
@rart should probably take a look too

**Comment by sumerjabri** [comment]
@rart please review

**Review by rart — APPROVED** [review]
@sumerjabri I'm not sure the samples we're attaching here into the docs are too valuable and these live in GitHub repos so having them here is more stuff to maintain as they evolve on their repo.

**Comment by sumerjabri** [comment]
@alhambrav would it be possible to simply link the docs to the samples in GitHub instead of putting the code in the docs?

**Review by sumerjabri — APPROVED** [review]

**Pull request merged**
